services:
  jekyll-container:
    build: .
    container_name: local_jekyll
    tty: true
    environment:
      - ENCRYPT_PASSWORD=$ENCRYPT_PASSWORD
    volumes:
      - .:/site
    ports:
      - "4000:4000"
